# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.5"
  - "3.6"

env:
  - TOXENV=travisci

# command to install dependencies
install: pip install -U tox

# command to run tests
script: tox
